version: '3'

services:
    server:
        image: php:7.4-apache

        volumes: 
            - ./app:/var/www/html
        ports:
            - 82:80
#Subirlo a la nube con docker-compose up